version: '3'

services:
  redis:
    image: 'redis:3.2-alpine'
    ports:
      - '6379:6379'
    volumes:
      - 'redis:/data'

  web:
    build:  '.'
    # Use this to force name image
    image:  'miroadamy/web2:1.0-comp'

    depends_on:
      - 'redis'
    
    env_file:
      - '.env'  
    ports:
      - '5000:5000'

    volumes:
    - '.:/app'
      
volumes:
  redis: {}
